"""Generate a curated markdown tearsheet from a notebook + cached manifests.

A tearsheet is a **curated, auto-generated view** of a notebook —
markdown narration, key figures, and JSON summaries laid out for reading
(or printing). Unlike :func:`export_md` which dumps every cell with its
outputs, ``export_tearsheet`` skips code source by default and only
surfaces the artifacts that map cleanly to markdown (images + small JSON).

Inclusion rules:

- **Markdown cells** — included verbatim.
- **Code cells with image artifacts** (``.png`` / ``.svg`` / ``.jpg``) —
  inlined with relative paths so GitHub renders them in-place.
- **Code cells with JSON artifacts** — top-level keys rendered as a
  two-column table (nested dicts flatten to ``a.b`` keys).
- **Code cells tagged ``kind=setup``** — source shown as a fenced block
  (hyperparams surface naturally).
- Everything else (plain ``step`` cells, parquet artifacts, stream output,
  display-data blobs) is skipped.

## Artifact filtering — ``tearsheet`` tag (opt-in)

For notebooks with many intermediate debug artifacts, mark the subset
that belongs on the polished tearsheet with the ``tearsheet`` tag,
either on the cell or on the artifact:

    # Cell-level tag — all artifacts from this cell are included.
    # %% tags=["jc.figure", "name=fig1", "tearsheet"]
    jc.figure("artifacts/headline.png", caption="Main result")

    # Or artifact-level — fine-grained (a cell can produce multiple
    # artifacts, only some tearsheet-worthy):
    jc.save(debug_dict, "artifacts/debug.json")                # excluded
    jc.save(headline, "artifacts/headline.json",
            tags=["tearsheet"])                                # included

Filtering is auto-enabled when **any** artifact in the run carries
the ``tearsheet`` tag (cell- or artifact-level). A notebook with no
tagging behaves exactly as before — every renderable artifact is
inlined — so the feature is strictly additive.

Default output is ``manuscripts/tearsheets/<stem>.md``. That subfolder
convention keeps auto-generated files out of the hand-authored work that
lives at the root of ``manuscripts/`` — paper drafts, decision memos,
thesis chapters — which would otherwise get blown away on regenerate.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from jellycell.cache.manifest import Manifest
from jellycell.format import parse as format_parse
from jellycell.format.cells import Cell, Notebook

_IMAGE_EXTS = frozenset({"png", "svg", "jpg", "jpeg", "gif", "webp"})
_TEARSHEET_TAG = "tearsheet"


def export_tearsheet(
    notebook_path: Path,
    manifests_by_cell: dict[str, Manifest],
    output_path: Path,
    project_root: Path,
) -> Path:
    """Write a curated markdown tearsheet for ``notebook_path`` to ``output_path``.

    Args:
        notebook_path: Source ``.py`` notebook.
        manifests_by_cell: Map of ``{notebook_stem}:{ordinal}`` → :class:`Manifest`.
        output_path: Target file. Parent directories are created.
        project_root: Project root — used to resolve artifact paths relative
            to ``output_path``'s parent.
    """
    nb = format_parse(notebook_path)
    stem = notebook_path.stem
    notebook_rel = notebook_path.resolve().relative_to(project_root.resolve())
    out_dir = output_path.parent.resolve()
    tearsheet_cell_ids = _cells_tagged_tearsheet(nb, stem)
    tearsheet_only = _any_tearsheet_tag(manifests_by_cell, tearsheet_cell_ids)

    lines: list[str] = []
    title, title_cell_ordinal = _extract_title(nb, fallback=stem)
    lines.append(f"# {title}")
    lines.append("")

    lines.extend(_header_lines(notebook_rel, out_dir, project_root, manifests_by_cell))
    lines.append("")

    for ordinal, cell in enumerate(nb.cells):
        cell_lines = _render_cell(
            cell=cell,
            ordinal=ordinal,
            stem=stem,
            manifests_by_cell=manifests_by_cell,
            out_dir=out_dir,
            project_root=project_root,
            skip_title_ordinal=title_cell_ordinal,
            tearsheet_only=tearsheet_only,
            tearsheet_cell_ids=tearsheet_cell_ids,
        )
        if cell_lines:
            lines.extend(cell_lines)
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*Auto-generated by `jellycell export tearsheet "
        f"{notebook_rel}`. Regenerating overwrites this file — for "
        "hand-authored writeups put a `.md` at the root of `manuscripts/` "
        "instead of under `tearsheets/`.*"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output_path


def _cells_tagged_tearsheet(nb: Notebook, stem: str) -> set[str]:
    """Return cell_ids whose raw metadata tags include ``tearsheet``.

    Tags at the cell level mark every artifact the cell produces as
    tearsheet-worthy. Complements artifact-level ``tags=["tearsheet"]``
    on ``jc.*`` calls, which is finer-grained.
    """
    out: set[str] = set()
    for ordinal, cell in enumerate(nb.cells):
        raw_tags = cell.metadata.get("tags", [])
        if isinstance(raw_tags, list) and _TEARSHEET_TAG in raw_tags:
            out.add(f"{stem}:{ordinal}")
    return out


def _any_tearsheet_tag(
    manifests_by_cell: dict[str, Manifest], tearsheet_cell_ids: set[str]
) -> bool:
    """Determine whether tag-based filtering should kick in for this notebook.

    Returns ``True`` when at least one cell or artifact carries the
    ``tearsheet`` tag — in which case the exporter includes only tagged
    artifacts. When nothing is tagged, we keep the legacy include-everything
    behavior (strictly additive upgrade).
    """
    if tearsheet_cell_ids:
        return True
    for manifest in manifests_by_cell.values():
        for art in manifest.artifacts:
            if _TEARSHEET_TAG in art.tags:
                return True
    return False


def _artifact_passes_filter(
    art: Any, cell_id: str, tearsheet_only: bool, tearsheet_cell_ids: set[str]
) -> bool:
    """Return whether ``art`` should be inlined given the current filter.

    When ``tearsheet_only`` is off, everything passes — legacy behavior.
    When on, the artifact must either carry the ``tearsheet`` tag itself
    or belong to a cell whose metadata tags include it.
    """
    if not tearsheet_only:
        return True
    if _TEARSHEET_TAG in art.tags:
        return True
    return cell_id in tearsheet_cell_ids


def _extract_title(nb: Notebook, *, fallback: str) -> tuple[str, int | None]:
    """Return ``(title, ordinal_of_source_markdown_cell)`` or fall back to stem."""
    for ordinal, cell in enumerate(nb.cells):
        if cell.cell_type != "markdown":
            continue
        for line in cell.source.splitlines():
            stripped = line.strip()
            if stripped.startswith("# ") and not stripped.startswith("## "):
                return stripped[2:].strip(), ordinal
        # First markdown cell, no H1 → give up so we don't strip its first line.
        return fallback.replace("-", " ").replace("_", " ").title(), None
    return fallback.replace("-", " ").replace("_", " ").title(), None


def _header_lines(
    notebook_rel: Path,
    out_dir: Path,
    project_root: Path,
    manifests_by_cell: dict[str, Manifest],
) -> list[str]:
    """Clear provenance block: what this file is, what produced it, when.

    Renders as a blockquote so it sits apart from the body text without
    being a second heading. Includes a link to ``site/<stem>.html`` when
    one exists on disk — readers who want the richer view can click
    through.
    """
    nb_link = _relative(project_root / notebook_rel, out_dir)
    stem = notebook_rel.stem
    parts = [f"**Tearsheet** for [`{notebook_rel}`]({nb_link})"]

    html = project_root / "site" / f"{stem}.html"
    if html.exists():
        html_link = _relative(html, out_dir)
        parts.append(f"[HTML report]({html_link})")

    latest = _latest_executed_at(manifests_by_cell)
    if latest is not None:
        parts.append(f"last run `{latest.isoformat(timespec='seconds')}`")

    return ["> " + " · ".join(parts)]


def _render_cell(
    *,
    cell: Cell,
    ordinal: int,
    stem: str,
    manifests_by_cell: dict[str, Manifest],
    out_dir: Path,
    project_root: Path,
    skip_title_ordinal: int | None,
    tearsheet_only: bool,
    tearsheet_cell_ids: set[str],
) -> list[str]:
    """Render one cell into tearsheet lines. Empty list = skip."""
    if cell.cell_type == "markdown":
        return _render_markdown_cell(cell, ordinal, skip_title_ordinal)
    if cell.cell_type != "code":
        return []

    cell_id = f"{stem}:{ordinal}"
    manifest = manifests_by_cell.get(cell_id)
    lines: list[str] = []

    if cell.spec.kind == "setup":
        lines.extend(_render_setup_cell(cell))

    if manifest is not None:
        lines.extend(
            _render_image_artifacts(
                cell,
                manifest,
                out_dir,
                project_root,
                cell_id=cell_id,
                tearsheet_only=tearsheet_only,
                tearsheet_cell_ids=tearsheet_cell_ids,
            )
        )
        lines.extend(
            _render_json_artifacts(
                cell,
                manifest,
                project_root,
                cell_id=cell_id,
                tearsheet_only=tearsheet_only,
                tearsheet_cell_ids=tearsheet_cell_ids,
            )
        )

    return lines


def _render_markdown_cell(cell: Cell, ordinal: int, skip_title_ordinal: int | None) -> list[str]:
    text = cell.source.rstrip("\n")
    if ordinal != skip_title_ordinal:
        return [text] if text.strip() else []

    # Strip the H1 line we already used as the title; keep the rest.
    rest_lines = []
    seen_h1 = False
    for line in text.splitlines():
        if not seen_h1 and line.strip().startswith("# "):
            seen_h1 = True
            continue
        rest_lines.append(line)
    rest = "\n".join(rest_lines).strip()
    return [rest] if rest else []


def _render_setup_cell(cell: Cell) -> list[str]:
    label = cell.spec.name or "Parameters"
    return [
        f"**{_humanize(label)}**",
        "",
        "```python",
        cell.source.rstrip("\n"),
        "```",
    ]


def _render_image_artifacts(
    cell: Cell,
    manifest: Manifest,
    out_dir: Path,
    project_root: Path,
    *,
    cell_id: str,
    tearsheet_only: bool,
    tearsheet_cell_ids: set[str],
) -> list[str]:
    """Inline each image artifact with optional caption/notes/tags trailers.

    Layout for a figure with metadata:

        **Figure caption**

        ![alt](../../artifacts/plot.png)
        *Notes paragraph here.*

        _tags: regression, diagnostic_

    Without a caption we fall back to the old behavior (bare image with
    cell-name alt text).
    """
    lines: list[str] = []
    for art in manifest.artifacts:
        if not _artifact_passes_filter(art, cell_id, tearsheet_only, tearsheet_cell_ids):
            continue
        ext = art.path.rsplit(".", 1)[-1].lower() if "." in art.path else ""
        if ext not in _IMAGE_EXTS:
            continue
        rel = _relative(project_root / art.path, out_dir)
        alt = cell.spec.name or Path(art.path).stem.replace("_", " ")
        if art.caption:
            lines.append(f"**{art.caption}**")
            lines.append("")
        lines.append(f"![{alt}]({rel})")
        if art.notes:
            lines.append(f"*{art.notes}*")
        if art.tags:
            lines.append(f"_tags: {', '.join(art.tags)}_")
        lines.append("")
    return lines


def _render_json_artifacts(
    cell: Cell,
    manifest: Manifest,
    project_root: Path,
    *,
    cell_id: str,
    tearsheet_only: bool,
    tearsheet_cell_ids: set[str],
) -> list[str]:
    """Flatten JSON artifacts into a two-column table.

    Label precedence: explicit ``caption`` from the ``jc.save(..., caption=...)``
    call, then the file stem (so two JSONs from the same cell stay
    distinguishable), then a humanized fallback. Notes and tags trail the
    table when present.
    """
    _ = cell
    lines: list[str] = []
    for art in manifest.artifacts:
        if not _artifact_passes_filter(art, cell_id, tearsheet_only, tearsheet_cell_ids):
            continue
        if not art.path.endswith(".json"):
            continue
        abs_path = project_root / art.path
        try:
            data = json.loads(abs_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if not isinstance(data, dict):
            continue
        label = art.caption or _humanize(Path(art.path).stem)
        lines.append(f"**{label}**")
        lines.append("")
        lines.append("| field | value |")
        lines.append("| --- | --- |")
        for k, v in _flatten(data).items():
            lines.append(f"| `{k}` | {_fmt_value(v)} |")
        if art.notes:
            lines.append("")
            lines.append(f"*{art.notes}*")
        if art.tags:
            lines.append("")
            lines.append(f"_tags: {', '.join(art.tags)}_")
        lines.append("")
    return lines


def _flatten(
    data: dict[str, Any], prefix: str = "", out: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Flatten nested dicts into dotted keys. Lists stay as-is."""
    if out is None:
        out = {}
    for k, v in data.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            _flatten(v, prefix=f"{key}.", out=out)
        else:
            out[key] = v
    return out


def _fmt_value(value: Any) -> str:
    """Render a value cell for the markdown table. Keeps things compact."""
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, int | float):
        formatted = f"{value:.4g}" if isinstance(value, float) else str(value)
        return f"`{formatted}`"
    if isinstance(value, list):
        if len(value) <= 6:
            inner = ", ".join(_fmt_scalar(x) for x in value)
            return f"`[{inner}]`"
        return f"`[{len(value)} items]`"
    if value is None:
        return "`null`"
    text = str(value).replace("|", "\\|").replace("\n", " ")
    if len(text) > 80:
        text = text[:77] + "…"
    return text


def _fmt_scalar(value: Any) -> str:
    if isinstance(value, str):
        return repr(value)
    return str(value)


def _humanize(name: str) -> str:
    return name.replace("_", " ").replace("-", " ").strip().capitalize()


def _latest_executed_at(manifests: dict[str, Manifest]) -> datetime | None:
    times = [m.executed_at for m in manifests.values() if m.executed_at is not None]
    return max(times) if times else None


def _relative(target: Path, start: Path) -> str:
    """POSIX-style relative path from ``start`` to ``target`` (markdown-safe)."""
    rel = os.path.relpath(target, start)
    return Path(rel).as_posix()


__all__ = ["export_tearsheet"]
