"""Generate a curated markdown tearsheet from a notebook + cached manifests.

A tearsheet is a **curated view** of a notebook — markdown narration, key
figures, and JSON summaries laid out for reading (or printing). Unlike
:func:`export_md` which dumps every cell with its outputs, ``export_tearsheet``
skips code source by default and only surfaces the artifacts that map
cleanly to markdown (images and small JSON summaries).

Inclusion rules:

- **Markdown cells** — included verbatim.
- **Code cells with image artifacts** (``.png`` / ``.svg`` / ``.jpg``) —
  inlined with relative paths so GitHub renders them in-place.
- **Code cells with JSON artifacts** — top-level keys rendered as a
  two-column table (nested dicts flatten to ``a.b`` keys).
- **Code cells tagged ``kind=setup``** — source shown as a fenced block
  (hyperparams surface naturally).
- Everything else (plain ``step`` cells, parquet artifacts, stream output,
  display-data blobs) is skipped. Authors edit the generated file by hand
  where they want more.

Output target defaults to ``manuscripts/<stem>.md`` — relative paths
assume that layout.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from jellycell.cache.manifest import Manifest
from jellycell.format import parse as format_parse
from jellycell.format.cells import Cell, Notebook

_IMAGE_EXTS = frozenset({"png", "svg", "jpg", "jpeg", "gif", "webp"})


def export_tearsheet(
    notebook_path: Path,
    manifests_by_cell: dict[str, Manifest],
    output_path: Path,
    project_root: Path,
) -> Path:
    """Write a curated markdown tearsheet for ``notebook_path`` to ``output_path``.

    Args:
        notebook_path: Source ``.py`` notebook.
        manifests_by_cell: Map of ``{notebook_stem}:{ordinal}`` → :class:`Manifest`.
        output_path: Target file. Parent directories are created.
        project_root: Project root — used to resolve artifact paths relative
            to ``output_path``'s parent.
    """
    nb = format_parse(notebook_path)
    stem = notebook_path.stem
    notebook_rel = notebook_path.resolve().relative_to(project_root.resolve())
    out_dir = output_path.parent.resolve()

    lines: list[str] = []
    title, title_cell_ordinal = _extract_title(nb, fallback=stem)
    lines.append(f"# {title}")
    lines.append("")

    subtitle = _subtitle(notebook_rel, out_dir, project_root, manifests_by_cell)
    if subtitle:
        lines.append(subtitle)
        lines.append("")

    for ordinal, cell in enumerate(nb.cells):
        cell_lines = _render_cell(
            cell=cell,
            ordinal=ordinal,
            stem=stem,
            manifests_by_cell=manifests_by_cell,
            out_dir=out_dir,
            project_root=project_root,
            skip_title_ordinal=title_cell_ordinal,
        )
        if cell_lines:
            lines.extend(cell_lines)
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by `jellycell export tearsheet "
        f"{notebook_rel}`. Edit freely — regenerate any time.*"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output_path


def _extract_title(nb: Notebook, *, fallback: str) -> tuple[str, int | None]:
    """Return ``(title, ordinal_of_source_markdown_cell)`` or fall back to stem."""
    for ordinal, cell in enumerate(nb.cells):
        if cell.cell_type != "markdown":
            continue
        for line in cell.source.splitlines():
            stripped = line.strip()
            if stripped.startswith("# ") and not stripped.startswith("## "):
                return stripped[2:].strip(), ordinal
        # First markdown cell, no H1 → give up so we don't strip its first line.
        return fallback.replace("-", " ").replace("_", " ").title(), None
    return fallback.replace("-", " ").replace("_", " ").title(), None


def _subtitle(
    notebook_rel: Path,
    out_dir: Path,
    project_root: Path,
    manifests_by_cell: dict[str, Manifest],
) -> str:
    """A single-line subheader with source link + (optional) timestamp."""
    rel = _relative(project_root / notebook_rel, out_dir)
    parts = [f"Source: [`{notebook_rel}`]({rel})"]
    latest = _latest_executed_at(manifests_by_cell)
    if latest is not None:
        parts.append(f"last run `{latest.isoformat(timespec='seconds')}`")
    return "> " + " · ".join(parts)


def _render_cell(
    *,
    cell: Cell,
    ordinal: int,
    stem: str,
    manifests_by_cell: dict[str, Manifest],
    out_dir: Path,
    project_root: Path,
    skip_title_ordinal: int | None,
) -> list[str]:
    """Render one cell into tearsheet lines. Empty list = skip."""
    if cell.cell_type == "markdown":
        return _render_markdown_cell(cell, ordinal, skip_title_ordinal)
    if cell.cell_type != "code":
        return []

    manifest = manifests_by_cell.get(f"{stem}:{ordinal}")
    lines: list[str] = []

    if cell.spec.kind == "setup":
        lines.extend(_render_setup_cell(cell))

    if manifest is not None:
        lines.extend(_render_image_artifacts(cell, manifest, out_dir, project_root))
        lines.extend(_render_json_artifacts(cell, manifest, project_root))

    return lines


def _render_markdown_cell(cell: Cell, ordinal: int, skip_title_ordinal: int | None) -> list[str]:
    text = cell.source.rstrip("\n")
    if ordinal != skip_title_ordinal:
        return [text] if text.strip() else []

    # Strip the H1 line we already used as the title; keep the rest.
    rest_lines = []
    seen_h1 = False
    for line in text.splitlines():
        if not seen_h1 and line.strip().startswith("# "):
            seen_h1 = True
            continue
        rest_lines.append(line)
    rest = "\n".join(rest_lines).strip()
    return [rest] if rest else []


def _render_setup_cell(cell: Cell) -> list[str]:
    label = cell.spec.name or "Parameters"
    return [
        f"**{_humanize(label)}**",
        "",
        "```python",
        cell.source.rstrip("\n"),
        "```",
    ]


def _render_image_artifacts(
    cell: Cell, manifest: Manifest, out_dir: Path, project_root: Path
) -> list[str]:
    lines: list[str] = []
    for art in manifest.artifacts:
        ext = art.path.rsplit(".", 1)[-1].lower() if "." in art.path else ""
        if ext not in _IMAGE_EXTS:
            continue
        rel = _relative(project_root / art.path, out_dir)
        caption = cell.spec.name or Path(art.path).stem.replace("_", " ")
        lines.append(f"![{caption}]({rel})")
        lines.append("")
    return lines


def _render_json_artifacts(cell: Cell, manifest: Manifest, project_root: Path) -> list[str]:
    # Using the artifact's file stem (not the cell's name) disambiguates
    # the common case where one cell saves several JSONs — e.g. a
    # ``summary`` cell that writes both ``summary.json`` and ``totals.json``.
    _ = cell
    lines: list[str] = []
    for art in manifest.artifacts:
        if not art.path.endswith(".json"):
            continue
        abs_path = project_root / art.path
        try:
            data = json.loads(abs_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if not isinstance(data, dict):
            continue
        label = Path(art.path).stem
        lines.append(f"**{_humanize(label)}**")
        lines.append("")
        lines.append("| field | value |")
        lines.append("| --- | --- |")
        for k, v in _flatten(data).items():
            lines.append(f"| `{k}` | {_fmt_value(v)} |")
        lines.append("")
    return lines


def _flatten(
    data: dict[str, Any], prefix: str = "", out: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Flatten nested dicts into dotted keys. Lists stay as-is."""
    if out is None:
        out = {}
    for k, v in data.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            _flatten(v, prefix=f"{key}.", out=out)
        else:
            out[key] = v
    return out


def _fmt_value(value: Any) -> str:
    """Render a value cell for the markdown table. Keeps things compact."""
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, int | float):
        formatted = f"{value:.4g}" if isinstance(value, float) else str(value)
        return f"`{formatted}`"
    if isinstance(value, list):
        if len(value) <= 6:
            inner = ", ".join(_fmt_scalar(x) for x in value)
            return f"`[{inner}]`"
        return f"`[{len(value)} items]`"
    if value is None:
        return "`null`"
    text = str(value).replace("|", "\\|").replace("\n", " ")
    if len(text) > 80:
        text = text[:77] + "…"
    return text


def _fmt_scalar(value: Any) -> str:
    if isinstance(value, str):
        return repr(value)
    return str(value)


def _humanize(name: str) -> str:
    return name.replace("_", " ").replace("-", " ").strip().capitalize()


def _latest_executed_at(manifests: dict[str, Manifest]) -> datetime | None:
    times = [m.executed_at for m in manifests.values() if m.executed_at is not None]
    return max(times) if times else None


def _relative(target: Path, start: Path) -> str:
    """POSIX-style relative path from ``start`` to ``target`` (markdown-safe)."""
    rel = os.path.relpath(target, start)
    return Path(rel).as_posix()


__all__ = ["export_tearsheet"]
