"""Shared header + helper rendering for :mod:`jellycell.tearsheets`.

Every helper in :mod:`jellycell.tearsheets` emits a manuscript-style
markdown file with a consistent, pinnable header block so the output
is byte-stable across runs when the caller passes
``template_overrides`` (author, month_year, version, author_url).

Kept private; the public surface is the three helper functions in
:mod:`jellycell.tearsheets` (``findings``, ``methodology``, ``audit``).
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from jellycell._version import __version__

__all__ = [
    "DEFAULT_TEMPLATE_FIELDS",
    "render_frontmatter_block",
    "render_header",
    "render_key_value_table",
    "resolve_template_fields",
]


DEFAULT_TEMPLATE_FIELDS: dict[str, str] = {
    "author": "",
    "author_url": "",
    "month_year": "",  # filled at render time if not overridden
    "version": __version__,
}


def resolve_template_fields(overrides: dict[str, str] | None) -> dict[str, str]:
    """Merge caller overrides over defaults, filling ``month_year`` from now if absent."""
    fields = dict(DEFAULT_TEMPLATE_FIELDS)
    if overrides:
        fields.update(overrides)
    if not fields["month_year"]:
        fields["month_year"] = datetime.now().strftime("%B %Y")
    return fields


def render_header(
    *,
    kind: str,
    title: str,
    subtitle: str,
    project: str,
    template_overrides: dict[str, str] | None,
) -> str:
    """Render the top-of-file header shared across all tearsheet helpers.

    ``kind`` is one of ``findings`` / ``methodology`` / ``audit`` and shows
    up in an HTML comment so regeneration origin is obvious. The header
    line carries project name, author (+ optional URL), month_year, and
    jellycell version — all pinnable via ``template_overrides`` for
    byte-stable regen.
    """
    fields = resolve_template_fields(template_overrides)
    author_blob = fields["author"] or "—"
    if fields["author"] and fields["author_url"]:
        author_blob = f"[{fields['author']}]({fields['author_url']})"
    return (
        f"<!-- Auto-generated by jellycell.tearsheets.{kind}. "
        f"Edit the source notebook / inputs, not this file. -->\n\n"
        f"# {title}\n\n"
        f"{subtitle}\n\n"
        f"*Project: **{project}** · Author: {author_blob} · "
        f"{fields['month_year']} · jellycell {fields['version']}*\n\n"
        f"---\n\n"
    )


def render_key_value_table(rows: dict[str, Any], *, key_header: str = "Metric") -> str:
    """Render a two-column markdown table from ``{key: value}`` pairs.

    Values are formatted with :func:`_format_value` — bools / numbers get
    inline code ticks, lists collapse to ``[n items]`` when long, ``None``
    becomes ``null``. Nested dicts flatten with dotted keys so
    ``{"cs": {"att": 0.2}}`` becomes a ``cs.att`` row.
    """
    flat = _flatten(rows)
    if not flat:
        return ""
    lines = [f"| {key_header} | Value |", "| --- | --- |"]
    for k, v in flat.items():
        lines.append(f"| `{k}` | {_format_value(v)} |")
    return "\n".join(lines) + "\n"


def render_frontmatter_block(fields: dict[str, str]) -> str:
    """Emit a plain JSON block that's machine-parseable and GitHub-renderable.

    Some teams pin extra metadata (PR number, DOI, dataset snapshot id)
    beyond the header fields. This block lets downstream tooling recover
    those values without re-parsing the header.
    """
    if not fields:
        return ""
    return "```json\n" + json.dumps(fields, indent=2, sort_keys=True) + "\n```\n\n"


def _flatten(
    data: dict[str, Any], prefix: str = "", out: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Flatten nested dicts to dotted keys; non-dict values pass through."""
    if out is None:
        out = {}
    for k, v in data.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            _flatten(v, prefix=f"{key}.", out=out)
        else:
            out[key] = v
    return out


def _format_value(value: Any) -> str:
    """Render a single value cell for the markdown table — compact + safe."""
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, int | float):
        formatted = f"{value:.4g}" if isinstance(value, float) else str(value)
        return f"`{formatted}`"
    if isinstance(value, list):
        if len(value) <= 6:
            inner = ", ".join(_scalar(x) for x in value)
            return f"`[{inner}]`"
        return f"`[{len(value)} items]`"
    if value is None:
        return "`null`"
    text = str(value).replace("|", "\\|").replace("\n", " ")
    if len(text) > 80:
        text = text[:77] + "…"
    return text


def _scalar(value: Any) -> str:
    if isinstance(value, str):
        return repr(value)
    return str(value)


def ensure_output_path(out_path: str | Path) -> Path:
    """Resolve + create parent directories for an output path."""
    target = Path(out_path).expanduser()
    target.parent.mkdir(parents=True, exist_ok=True)
    return target
